[package]
name = "clay-gui"
version = "0.0.1"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

description = "User interface for Clay - an OpenCL ray/path tracer"
homepage = "https://github.com/nthend/clay"
repository = "https://github.com/nthend/clay"
readme = "README.md"

keywords = ["ray-tracing", "path-tracing", "opencl"]
categories = ["graphics", "rendering", "multimedia"]

[dependencies]
clay-core = { path = "../clay-core" }
nalgebra = "0.18"
sdl2 = "0.32"
